name: "Code Generation"

on: workflow_dispatch

permissions:
  contents: write

jobs:
  generation-job:
    runs-on: ubuntu-latest
    container:
      image: openapitools/openapi-generator-cli:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run code generation
        run: (bash /usr/local/bin/docker-entrypoint.sh generate -i blob/v0.0.1.json --additional-properties moduleName=VultRuby --skip-validate-spec -g ruby -o ./vendor/vultr_ruby)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
